# Generated by Django 5.1.2 on 2024-10-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.PositiveBigIntegerField()),
                ('inventory', models.PositiveBigIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='media/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.category')),
            ],
        ),
    ]
