# Generated by Django 5.1.2 on 2024-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.charfield>', max_length=200),
        ),
    ]
