# Generated by Django 5.1.2 on 2024-11-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_level_category_lft_category_rght_and_more'),
        ('store', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_categories', to='store.product'),
        ),
    ]
